# Generated by Django 5.0.3 on 2024-03-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='picture/%Y/%M'),
        ),
    ]
